title: Oleg Gordienko â€“ Front End Developer

markdown: kramdown
kramdown:
    input: GFM

defaults:
    -
        scope:
            path: "" # an empty string - all files in the project
        values:
            layout: "default"

destination: .site
sass:
    style: :compressed
